version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      HTTP_PROXY: "http://proxy-dmz.intel.com:911/"
      HTTPS_PROXY: "http://proxy-dmz.intel.com:912/"
      NO_PROXY: "localhost,127.0.0.0/8"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsaggr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    environment:
      HTTP_PROXY: "http://proxy-dmz.intel.com:911/"
      HTTPS_PROXY: "http://proxy-dmz.intel.com:912/"
      NO_PROXY: "localhost,127.0.0.0/8"
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      args:
        HTTP_PROXY: "http://proxy-dmz.intel.com:911"
        HTTPS_PROXY: "http://proxy-dmz.intel.com:912"
        NO_PROXY: "localhost,127.0.0.0/8"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  celery_worker:
    build: ./backend
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
